language: scala
sudo: false
jdk:
  - oraclejdk8
dist: trusty
scala:
  - 2.11.12
  - 2.12.1
  - 2.13.1
env:
  - SCALAJS_VERSION=0.6.29
  - SCALAJS_VERSION=1.1.0
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
